[package]
name = "fhe-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.5.1", features = [ "boolean", "shortint", "integer", "x86_64-unix" ] }
bincode = "1.3.3"
glob = "0.3.1"
rayon = "1.8.1"